services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: echo
      POSTGRES_DB: echo
    ports:
      - "5432:5432"
    volumes:
      echo_pgdata:/var/lib/postgresql/data

volumes:
  echo_pgdata:
