"""Green implementation of :class:`WhatsAppProvisioner`.

Translates provider-neutral provisioning calls into Green ``GreenClient``
calls. Green-specific identifiers (``idInstance``, ``apiTokenInstance``)
live only here and in :mod:`echo_v2.integrations.green.client`.

Credentials carry **only** the API token; ``idInstance`` comes from
``ConnectionRef.provider_connection_id`` (plan decision 13). A single
``_require_credentials`` helper handles missing credentials uniformly (plan
guardrail G9).
"""

from __future__ import annotations

from echo_v2.integrations.green.client import GreenClient
from echo_v2.integrations.green.models import subscription_to_green_fields
from echo_v2.ports.whatsapp import (
    ConnectionConfig,
    ConnectionRef,
    ConnectionStatusSnapshot,
    CreatedConnection,
    CredentialResolver,
    PairingOutcome,
    PairingQr,
    PairingResult,
    ProviderCredentials,
)
from echo_v2.runtime.errors import PermanentError

__all__ = ["GreenProvisioner"]


class GreenProvisioner:
    """Green API implementation of :class:`WhatsAppProvisioner`."""

    def __init__(
        self,
        client: GreenClient,
        credential_resolver: CredentialResolver,
    ) -> None:
        self._client = client
        self._resolver = credential_resolver

    async def create_connection(
        self,
        config: ConnectionConfig,
    ) -> CreatedConnection:
        """Create and configure a Green instance in one partner call.

        Green's ``createInstance`` accepts ``webhookUrl``, ``webhookUrlToken``,
        and all five webhook switches in the initial call, so create + configure
        is a single operation (plan decision 5). The ``webhook_token`` was
        generated by the application and is passed through unchanged.
        """
        payload: dict[str, object] = {
            **subscription_to_green_fields(config.subscriptions),
            "webhookUrl": config.webhook_url,
            "webhookUrlToken": config.webhook_token,
        }
        data = await self._client.create_instance(payload)
        try:
            id_instance = str(data["idInstance"])
            api_token = str(data["apiTokenInstance"])
        except KeyError as exc:
            raise PermanentError(
                "createInstance response missing required field"
            ) from exc
        ref = ConnectionRef(provider="green", provider_connection_id=id_instance)
        # Credentials carry ONLY the api token. idInstance lives in the ref.
        credentials = ProviderCredentials(data=api_token.encode("utf-8"))
        return CreatedConnection(ref=ref, credentials=credentials)

    async def configure_connection(
        self,
        connection: ConnectionRef,
        config: ConnectionConfig,
    ) -> None:
        """Apply webhook/subscription settings to an existing instance."""
        api_token = await self._require_credentials(connection)
        settings: dict[str, object] = {
            **subscription_to_green_fields(config.subscriptions),
            "webhookUrl": config.webhook_url,
            "webhookUrlToken": config.webhook_token,
        }
        await self._client.set_settings(
            connection.provider_connection_id,
            api_token,
            settings,
        )

    async def get_status(
        self,
        connection: ConnectionRef,
    ) -> ConnectionStatusSnapshot:
        from echo_v2.integrations.green.models import map_state

        api_token = await self._require_credentials(connection)
        raw = await self._client.get_state_instance(
            connection.provider_connection_id,
            api_token,
        )
        return ConnectionStatusSnapshot(
            status=map_state(raw),
            provider_raw_status=raw,
        )

    async def get_pairing_qr(
        self,
        connection: ConnectionRef,
    ) -> PairingResult:
        api_token = await self._require_credentials(connection)
        result = await self._client.get_qr_ws(
            connection.provider_connection_id,
            api_token,
        )
        return _qr_result(result)

    async def unpair(
        self,
        connection: ConnectionRef,
    ) -> None:
        api_token = await self._require_credentials(connection)
        await self._client.logout(connection.provider_connection_id, api_token)

    async def delete_connection(
        self,
        connection: ConnectionRef,
    ) -> None:
        # deleteInstance uses the partner token, not the per-instance token.
        await self._client.delete_instance(connection.provider_connection_id)

    # -- helpers ----------------------------------------------------------

    async def _require_credentials(self, ref: ConnectionRef) -> str:
        """Decode the API token for ``ref`` or raise.

        A missing credential is a data-integrity problem (the connection
        record was lost or never persisted), not a transient failure -- raise
        :class:`PermanentError` so the runtime does not retry.
        """
        credentials = await self._resolver.get_credentials(ref)
        if credentials is None:
            raise PermanentError(
                f"no credentials stored for connection {ref.provider}:"
                f"{ref.provider_connection_id}"
            )
        return credentials.data.decode("utf-8")


def _qr_result(raw: dict[str, object]) -> PairingResult:
    etype = raw.get("type")
    message = raw.get("message")
    if etype == "qrCode":
        image = str(message) if message is not None else ""
        return PairingResult(
            outcome=PairingOutcome.QR_READY,
            qr=PairingQr(image_base64=image),
        )
    if etype == "alreadyLogged":
        return PairingResult(outcome=PairingOutcome.ALREADY_AUTHORIZED)
    if etype == "passkeyRequired":
        return PairingResult(
            outcome=PairingOutcome.PASSKEY_REQUIRED,
            message=str(message) if message is not None else "passkey required",
        )
    # timeout and error both surface as TIMEOUT for the caller's purposes;
    # the message retains the distinction for diagnostics.
    return PairingResult(
        outcome=PairingOutcome.TIMEOUT,
        message=str(message) if message is not None else "pairing timed out",
    )
