"""Small internal Guard review page."""

GUARD_DEBUG_PAGE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Guard shadow review</title>
<style>
body{font-family:system-ui,sans-serif;background:#f4f6f8;color:#17202a;margin:0}.wrap{max-width:1100px;margin:auto;padding:24px}
.filters,.card{background:#fff;border:1px solid #dfe5ea;border-radius:10px;padding:14px;margin-bottom:14px}.filters{display:flex;gap:8px;flex-wrap:wrap}
input,select,button,textarea{font:inherit;padding:7px;border:1px solid #c7d0d9;border-radius:6px}button{cursor:pointer;background:#f8fafb}.card h3{margin:0 0 4px}.muted{color:#65727e;font-size:.9rem}.pill{display:inline-block;border-radius:12px;padding:2px 8px;background:#e8eef5;margin:2px;font-size:.85rem}.row{margin-top:10px}.feedback button{margin-right:5px}.selected{outline:2px solid #2684ff}.error{color:#b42318}.evidence{margin:4px 0}.evidence button{width:28px;height:28px;padding:0;margin-right:6px;font-size:1.1rem}.evidence-text{display:none;margin:6px 0 8px;padding:8px;background:#f7f9fb;border-left:3px solid #2684ff;white-space:pre-wrap}.evidence-text.open{display:block}.evidence-meta{color:#65727e;font-size:.78rem}
</style></head><body><main class="wrap"><h1>Guard shadow review</h1><div id="status" class="muted">Loading…</div>
<form class="filters" onsubmit="load(event)"><select id="decision"><option value="">all decisions</option><option>none</option><option>watch</option><option>concerning</option><option>urgent</option></select><input id="category" placeholder="category"><input id="chat" placeholder="chat id"><input id="from" type="date"><input id="to" type="date"><button>Filter</button></form><section id="results"></section></main>
<script>
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function load(e){if(e)e.preventDefault();const p=new URLSearchParams();for(const [id,key] of [['decision','decision'],['category','category'],['chat','chat_id'],['from','date_from'],['to','date_to']]){const v=document.getElementById(id).value;if(v)p.set(key,v)}const r=await fetch('/api/debug/guard?'+p);if(r.status===401){location.href='/q/expired';return}if(!r.ok){document.getElementById('status').textContent='Error '+r.status;return}render(await r.json())}
function render(data){document.getElementById('status').textContent=data.total_results+' analyses';document.getElementById('results').innerHTML=data.results.map(x=>{const f=x.feedback;return `<article class="card"><h3>${esc(x.chat_name||x.chat_id)} <span class="pill">${esc(x.decision)}</span></h3><div class="muted">${esc(x.chat_id)} · child ${esc(x.child_user_id)} · ${esc(x.created_at)} · ${x.is_group?'group':'private'} · version ${x.target_version}</div><div class="row"><b>Progression:</b> ${esc(x.previous_decision||'none')} → ${esc(x.decision)}${x.activity_delta==null?'':' · activity +'+x.activity_delta}</div><div class="row"><b>Schedule:</b> ${esc(x.schedule_reason||'unavailable')} · scheduled ${esc(x.scheduled_for||'—')} · pending ${esc(x.pending_since||'—')}<br><span class="muted">scheduled delay ${fmt(x.scheduled_delay_seconds)} · actual ${fmt(x.actual_delay_seconds)} · lag ${fmt(x.scheduler_lag_seconds)}</span></div><div class="row"><b>Categories:</b> ${x.categories.map(v=>`<span class="pill">${esc(v)}</span>`).join('')}<br><b>Signals:</b> ${x.signals.map(v=>`<span class="pill">${esc(v)}</span>`).join('')}</div><div class="row"><b>Confidence:</b> ${x.confidence} · <b>Reason:</b> ${esc(x.reason)}</div><div class="row"><b>Evidence messages:</b> ${renderEvidence(x)} </div><div class="row feedback">${labels.map(([v,t])=>`<button class="${f&&f.label===v?'selected':''}" onclick="save('${esc(x.id)}','${v}')">${t}</button>`).join('')}<textarea id="note-${esc(x.id)}" placeholder="note">${esc(f&&f.note||'')}</textarea></div></article>`}).join('')||'<div class="card">No results</div>'}
function renderEvidence(x){if(!x.evidence_message_ids.length)return '<span class="muted">none</span>';const messages=Object.fromEntries((x.evidence_messages||[]).map(m=>[m.id,m]));return x.evidence_message_ids.map((id,i)=>{const m=messages[id];if(!m)return `<span class="pill">${esc(id)}</span>`;const key=esc(x.id+'-'+i);return `<span class="evidence"><button type="button" aria-label="Show evidence" onclick="toggleEvidence('${key}',this)">+</button><span class="pill">${esc(id)}</span><span class="evidence-text" id="evidence-${key}"><span class="evidence-meta">${esc(m.direction)} · ${esc(m.timestamp)}${m.sender?' · '+esc(m.sender):''}</span>\n${esc(m.text)}</span></span>`}).join('')}
function toggleEvidence(key,button){const el=document.getElementById('evidence-'+key);if(!el)return;const open=el.classList.toggle('open');button.textContent=open?'−':'+'}
const labels=[['correct','✅ correct'],['false_positive','❌ false positive'],['should_be_stronger','⚠️ should be stronger'],['irrelevant','💤 irrelevant']];function fmt(v){return v==null?'—':Math.round(v)+'s'}
async function save(id,label){const note=document.getElementById('note-'+id)?.value||null;const r=await fetch('/api/debug/guard/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({result_id:id,label,note})});if(r.ok)load();else alert('Could not save feedback')}
load();
</script></body></html>'''
