"""HTML for the deterministic Echo Guard demo replay page."""

from __future__ import annotations

__all__ = ["GUARD_DEMO_PAGE"]


GUARD_DEMO_PAGE = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Echo Guard — Snapshot replay</title>
<style>
:root{
  --ink:#183047;--muted:#6b7e8d;--line:#dce7ee;--surface:#fff;--bg:#f4f8fb;
  --blue:#2684ff;--blue-soft:#eaf3ff;--green:#1d9b69;--green-soft:#eaf8f1;
  --amber:#bf7600;--amber-soft:#fff5df;--red:#d9485f;--red-soft:#fff0f3;
  --shadow:0 18px 50px rgba(37,77,109,.10);--radius:22px
}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:
  radial-gradient(circle at 8% 0%,rgba(38,132,255,.12),transparent 28%),
  linear-gradient(180deg,#fbfdff 0%,var(--bg) 70%);color:var(--ink);
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;line-height:1.5}
button{font:inherit}button:focus-visible,summary:focus-visible{outline:3px solid #8fc2ff;outline-offset:3px}
.wrap{width:min(1180px,calc(100% - 40px));margin:0 auto}.topbar{display:flex;justify-content:space-between;align-items:center;padding:26px 0 16px}
.brand{font-size:1.35rem;font-weight:850;letter-spacing:-.04em}.brand span{color:var(--blue)}.eyebrow{color:var(--blue);font-size:.75rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.lang-switch{color:var(--blue);text-decoration:none;margin-left:6px}
.muted{color:var(--muted)}.intro{max-width:760px;padding:66px 0 48px}.intro h1{font-size:clamp(2.5rem,7vw,5.6rem);line-height:.98;letter-spacing:-.065em;margin:14px 0 24px}.intro p{font-size:1.2rem;color:var(--muted);max-width:650px;margin:0 0 28px}.proof{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}.proof span{border:1px solid var(--line);border-radius:999px;padding:7px 11px;background:rgba(255,255,255,.72);color:var(--muted);font-size:.8rem;font-weight:700}
.primary,.secondary{border:0;border-radius:13px;padding:13px 18px;font-weight:800;cursor:pointer;transition:transform .16s ease,box-shadow .16s ease}.primary{background:var(--blue);color:#fff;box-shadow:0 8px 20px rgba(38,132,255,.23)}.secondary{border:1px solid var(--line);background:#fff;color:var(--ink)}.primary:hover,.secondary:hover{transform:translateY(-1px)}button:disabled{cursor:not-allowed;opacity:.45;transform:none}
.demo{padding:15px 0 48px}.demo-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;margin-bottom:18px}.demo-head h1{font-size:clamp(1.7rem,3vw,2.6rem);line-height:1.05;letter-spacing:-.05em;margin:6px 0}.scenario-count{white-space:nowrap;color:var(--muted);font-size:.9rem}
.scenario-nav{display:flex;gap:8px;overflow:auto;padding:3px 0 13px;margin-bottom:12px}.scenario-nav button{flex:0 0 auto;border:1px solid var(--line);background:rgba(255,255,255,.8);color:var(--muted);border-radius:999px;padding:9px 13px;cursor:pointer;font-size:.85rem;font-weight:750}.scenario-nav button.active{border-color:#a9ceff;background:var(--blue-soft);color:#1768cf}
.story{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:24px}.story-title{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.story-title h2{margin:0 0 5px;font-size:clamp(1.4rem,3vw,2rem);letter-spacing:-.04em}.story-title p{margin:0;color:var(--muted)}.story-moment{padding:9px 12px;border-radius:999px;background:#f1f6fa;color:var(--muted);font-size:.78rem;font-weight:750;white-space:nowrap}
.timeline{display:flex;align-items:center;gap:7px;margin:23px 0 20px;overflow:auto;padding-bottom:2px}.timeline button{position:relative;display:flex;align-items:center;gap:7px;flex:1;min-width:100px;border:0;background:transparent;color:var(--muted);cursor:pointer;text-align:left;padding:0}.timeline button:not(:last-child):after{content:"";height:2px;background:var(--line);flex:1;margin-left:3px}.timeline button.done:not(:last-child):after,.timeline button.active:not(:last-child):after{background:#9dc9ff}.timeline .dot{width:27px;height:27px;display:grid;place-items:center;border-radius:50%;border:2px solid var(--line);background:#fff;font-size:.73rem;font-weight:850;flex:0 0 auto}.timeline button.done .dot,.timeline button.active .dot{border-color:var(--blue);color:var(--blue)}.timeline button.active .dot{background:var(--blue);color:#fff}.timeline small{white-space:nowrap;font-size:.72rem;font-weight:750}
.grid{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(300px,.9fr);gap:18px}.panel{border:1px solid var(--line);border-radius:18px;background:#fbfdff;overflow:hidden}.panel-head{padding:15px 17px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.panel-head h3{margin:0;font-size:.83rem;letter-spacing:.09em;text-transform:uppercase;color:var(--muted)}.chat{padding:18px;background:linear-gradient(180deg,#edf5fa,#f8fbfd);min-height:355px}.message{max-width:78%;padding:10px 12px;border-radius:15px;margin:0 0 10px;background:#fff;box-shadow:0 4px 12px rgba(28,67,96,.07);border:2px solid transparent;transition:border-color .25s,transform .25s}.message.child{margin-left:auto;background:#dff6e9;border-bottom-right-radius:5px}.message.other{margin-right:auto;border-bottom-left-radius:5px}.message.other_2,.message.other_3,.message.other_4{margin-right:auto;border-bottom-left-radius:5px}.message.latest{border-color:#7eb8ff;transform:translateX(2px)}.message.evidence{box-shadow:0 0 0 3px rgba(255,190,76,.55),0 5px 15px rgba(28,67,96,.10)}.message-meta{font-size:.68rem;color:var(--muted);margin-bottom:2px;font-weight:750}.message-text{font-size:1rem;white-space:pre-wrap;overflow-wrap:anywhere}.empty-chat{color:var(--muted);text-align:center;padding:80px 20px}
.guard{padding:18px}.status-row{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.status-label{color:var(--muted);font-size:.75rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.decision{font-size:clamp(1.8rem,4vw,3rem);font-weight:900;letter-spacing:-.07em;line-height:1;margin:5px 0 7px}.decision-none{color:var(--green)}.decision-watch{color:var(--amber)}.decision-concerning{color:#d76c00}.decision-urgent{color:var(--red)}.decision.pulse{animation:pulse .45s ease}.reason{font-size:1rem;margin:0 0 20px}.alert{border-radius:14px;padding:13px 14px;margin-bottom:19px;background:var(--green-soft);color:#17724e}.alert.notify{background:var(--red-soft);color:#a62d45}.alert strong{display:block;font-size:.78rem;letter-spacing:.08em;text-transform:uppercase;margin-bottom:3px}.signal-section{margin:17px 0}.signal-section h4{font-size:.76rem;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin:0 0 8px}.chips{display:flex;flex-wrap:wrap;gap:6px}.chip{display:inline-flex;align-items:center;border-radius:999px;padding:6px 9px;background:#edf3f7;color:#385064;font-size:.78rem;font-weight:700}.chip.new{background:var(--amber-soft);color:#966000}.chip.none{font-weight:500;color:var(--muted);background:#f3f6f8}.evidence-list{display:flex;flex-wrap:wrap;gap:7px}.evidence-button{border:1px solid #b6d5f8;background:#f2f8ff;color:#1768cf;border-radius:999px;padding:6px 9px;cursor:pointer;font-size:.78rem;font-weight:750}.details{margin-top:20px;border-top:1px solid var(--line);padding-top:12px}.details summary{cursor:pointer;color:var(--muted);font-size:.8rem;font-weight:750}.details pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f1f5f8;border-radius:10px;padding:10px;font-size:.7rem;color:#526575;max-height:190px;overflow:auto}
.controls{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:20px}.control-group{display:flex;gap:8px}.play{min-width:92px}.hint{font-size:.78rem;color:var(--muted)}.error{border:1px solid #f1bdc8;background:var(--red-soft);color:#a62d45;border-radius:14px;padding:15px;margin-top:18px}
@keyframes pulse{0%{opacity:.35;transform:translateY(5px)}100%{opacity:1;transform:none}}@media (prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
@media (max-width:800px){.wrap{width:min(100% - 24px,620px)}.topbar{padding-top:18px}.intro{padding:45px 0 32px}.story{padding:16px}.story-title{display:block}.story-moment{display:inline-block;margin-top:12px}.grid{grid-template-columns:1fr}.chat{min-height:250px}.message{max-width:88%}.controls{align-items:stretch;flex-direction:column}.control-group{justify-content:space-between}.control-group button{flex:1}.hint{text-align:center}}
</style>
</head>
<body>
<main class="wrap">
  <header class="topbar"><div class="brand">echo<span>guard</span></div><div class="eyebrow">Snapshot replay · <a class="lang-switch" href="/demo/guard/he">עברית</a></div></header>
  <section id="intro" class="intro">
    <div class="eyebrow">Based on the Guard evaluation suite</div>
    <h1>See danger emerge before it becomes obvious.</h1>
    <p>Step through real Guard evaluation scenarios one snapshot at a time. Watch the conversation change, see what Guard remembers, and see when its policy says it is time to notify a parent.</p>
    <button id="start" class="primary" type="button">Start demo</button>
    <div class="proof"><span>Five scenarios</span><span>Every checkpoint</span><span>Deterministic replay</span></div>
  </section>
  <section id="demo" class="demo" hidden>
    <div class="demo-head"><div><div class="eyebrow">Echo Guard demo</div><h1>Context changes the answer.</h1></div><div id="scenario-count" class="scenario-count"></div></div>
    <nav id="scenario-nav" class="scenario-nav" aria-label="Demo scenarios"></nav>
    <article class="story">
      <div class="story-title"><div><h2 id="story-title"></h2><p id="story-subtitle"></p></div><div id="story-moment" class="story-moment"></div></div>
      <div id="timeline" class="timeline" aria-label="Conversation snapshots"></div>
      <div class="grid">
        <section class="panel" aria-label="Conversation"><div class="panel-head"><h3>Conversation</h3><span id="prefix-label" class="muted"></span></div><div id="chat" class="chat"></div></section>
        <section class="panel" aria-label="Guard interpretation"><div class="panel-head"><h3>Echo Guard</h3><span id="snapshot-label" class="muted"></span></div><div class="guard">
          <div class="status-row"><div><div class="status-label">Current status</div><div id="decision" class="decision"></div></div></div>
          <p id="reason" class="reason"></p>
          <div id="alert" class="alert"><strong>Parent notification</strong><span></span></div>
          <div class="signal-section"><h4>New signal</h4><div id="new-signals" class="chips"></div></div>
          <div class="signal-section"><h4>Guard remembers</h4><div id="remembered-signals" class="chips"></div></div>
          <div class="signal-section"><h4>Evidence in this snapshot</h4><div id="evidence" class="evidence-list"></div></div>
          <details class="details"><summary>Under the hood</summary><pre id="raw-details"></pre></details>
        </div></section>
      </div>
      <div class="controls"><span class="hint">Use the arrows to reveal the next part of the conversation.</span><div class="control-group"><button id="restart" class="secondary" type="button">Restart</button><button id="previous" class="secondary" type="button">Previous</button><button id="play" class="secondary play" type="button">Play</button><button id="next" class="primary" type="button">Next snapshot</button></div></div>
    </article>
    <div id="load-error" class="error" hidden>Unable to load the demo replay. Please refresh and try again.</div>
  </section>
</main>
<script>
const decisionLabels={none:'CLEAR',watch:'WATCH',concerning:'CONCERNING',urgent:'URGENT'};
const signalLabels={offline_knowledge:'Knows offline details',personal_information_request:'Asks for personal information',routine_probing:'Asks about routine',location_request:'Asks for location',secrecy_request:'Requests secrecy',meeting_request:'Suggests a meeting',age_deception:'Contradicts their age',sexual_solicitation:'Sexual solicitation',intimate_image_request:'Requests a private image',sexual_coercion:'Sexual pressure',off_platform_migration:'Moves the conversation elsewhere',repeated_unwanted_contact:'Keeps contacting after a boundary',boundary_violation:'Crosses a boundary',threat:'Threat',coercive_demand:'Coercive demand',blackmail_or_extortion:'Blackmail or extortion',help_request:'Asks for help',fear_expression:'Expresses fear',hopelessness:'Expresses hopelessness',self_harm_expression:'Self-harm expression',repeated_targeting:'Repeated targeting',insult_or_humiliation:'Insult or humiliation',group_pile_on:'Group pile-on',exclusion:'Exclusion',coordinated_exclusion:'Coordinated exclusion',harmful_content_sharing:'Harmful content sharing',threat_to_share:'Threatens to share'};
const categoryLabels={suspicious_contact:'Suspicious contact',child_sexual_exploitation:'Child safety risk',harassment_or_coercion:'Harassment or coercion',distress:'Distress',bullying:'Bullying',social_exclusion:'Social exclusion',harmful_sharing:'Harmful sharing'};
const state={scenarios:[],scenarioIndex:0,snapshotIndex:0,timer:null,renderVersion:0};
const $=id=>document.getElementById(id);
const label=(value,labels)=>labels[value]||String(value).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
function chips(values,kind){const box=document.createDocumentFragment();if(!values.length){const empty=document.createElement('span');empty.className='chip none';empty.textContent=kind==='new'?'No new signal':'Nothing additional yet';box.append(empty);return box}for(const value of values){const chip=document.createElement('span');chip.className='chip'+(kind==='new'?' new':'');chip.textContent=label(value,signalLabels);box.append(chip)}return box}
function renderScenarioNav(){const nav=$('scenario-nav');nav.replaceChildren();state.scenarios.forEach((scenario,index)=>{const button=document.createElement('button');button.type='button';button.className=index===state.scenarioIndex?'active':'';button.textContent=`${index+1}. ${scenario.title}`;button.setAttribute('aria-current',index===state.scenarioIndex?'true':'false');button.onclick=()=>selectScenario(index);nav.append(button)})}
function renderTimeline(scenario){const timeline=$('timeline');timeline.replaceChildren();scenario.snapshots.forEach((snapshot,index)=>{const button=document.createElement('button');button.type='button';button.className=(index<state.snapshotIndex?'done ':'')+(index===state.snapshotIndex?'active':'');button.setAttribute('aria-label',`Snapshot ${index+1}, after ${snapshot.after_message_id}`);button.onclick=()=>{state.snapshotIndex=index;render()};const dot=document.createElement('span');dot.className='dot';dot.textContent=String(index+1);const small=document.createElement('small');small.textContent=`after ${snapshot.after_message_id}`;button.append(dot,small);timeline.append(button)})}
function renderChat(scenario,snapshot){const chat=$('chat');chat.replaceChildren();const visible=scenario.messages.slice(0,snapshot.prefix_length);const evidence=new Set(snapshot.cumulative.evidence_message_ids);for(const message of visible){const item=document.createElement('article');item.className=`message ${message.sender}${message.id===snapshot.new_message_id?' latest':''}${evidence.has(message.id)?' evidence':''}`;item.id=`message-${message.id}`;const meta=document.createElement('div');meta.className='message-meta';meta.textContent=message.sender==='child'?'Child':message.sender.replace('other','Contact ');const text=document.createElement('div');text.className='message-text';text.dir='auto';text.textContent=message.text;item.append(meta,text);chat.append(item)}if(!visible.length){const empty=document.createElement('div');empty.className='empty-chat';empty.textContent='The conversation has not started yet.';chat.append(empty)}}
function render(){const scenario=state.scenarios[state.scenarioIndex];if(!scenario)return;const snapshot=scenario.snapshots[state.snapshotIndex];$('scenario-count').textContent=`Scenario ${state.scenarioIndex+1} of ${state.scenarios.length}`;$('story-title').textContent=scenario.title;$('story-subtitle').textContent=scenario.subtitle;$('story-moment').textContent=scenario.moment;$('prefix-label').textContent=`${snapshot.prefix_length} messages`;$('snapshot-label').textContent=`Snapshot ${state.snapshotIndex+1} of ${scenario.snapshots.length}`;renderScenarioNav();renderTimeline(scenario);renderChat(scenario,snapshot);const decision=$('decision');decision.textContent=decisionLabels[snapshot.decision]||snapshot.decision;decision.className=`decision decision-${snapshot.decision} pulse`;requestAnimationFrame(()=>setTimeout(()=>decision.classList.remove('pulse'),480));$('reason').textContent=snapshot.raw.reason||'Guard found no active risk signal in this snapshot.';const alert=$('alert');alert.className=`alert${snapshot.should_alert?' notify':''}`;alert.querySelector('span').textContent=snapshot.should_alert?'Notify parent':'Not yet';$('new-signals').replaceChildren(chips(snapshot.new_signals,'new'));const remembered=snapshot.remembered_signals.length?snapshot.remembered_signals:snapshot.cumulative.signals;$('remembered-signals').replaceChildren(chips(remembered,'remembered'));const evidence=$('evidence');evidence.replaceChildren();if(!snapshot.raw.evidence_message_ids.length){const empty=document.createElement('span');empty.className='chip none';empty.textContent='No evidence cited';evidence.append(empty)}else for(const id of snapshot.raw.evidence_message_ids){const button=document.createElement('button');button.type='button';button.className='evidence-button';button.textContent=id;button.onclick=()=>focusMessage(id);evidence.append(button)}$('raw-details').textContent=JSON.stringify({raw:snapshot.raw,cumulative:snapshot.cumulative,decision:snapshot.decision,alert_policy:snapshot.should_alert?'notify_parent':'not_yet'},null,2);$('previous').disabled=state.scenarioIndex===0&&state.snapshotIndex===0;$('next').textContent=state.snapshotIndex===scenario.snapshots.length-1?(state.scenarioIndex===state.scenarios.length-1?'Replay complete':'Next scenario'):'Next snapshot'}
function focusMessage(id){const element=$(`message-${id}`);if(!element)return;element.scrollIntoView({behavior:'smooth',block:'center'});element.classList.remove('evidence');void element.offsetWidth;element.classList.add('evidence')}
function selectScenario(index){stopPlay();state.scenarioIndex=index;state.snapshotIndex=0;render();window.scrollTo({top:$('demo').offsetTop-12,behavior:'smooth'})}
function next(){const scenario=state.scenarios[state.scenarioIndex];if(state.snapshotIndex<scenario.snapshots.length-1){state.snapshotIndex++}else if(state.scenarioIndex<state.scenarios.length-1){state.scenarioIndex++;state.snapshotIndex=0}else{stopPlay();return}render()}
function previous(){if(state.snapshotIndex>0){state.snapshotIndex--}else if(state.scenarioIndex>0){state.scenarioIndex--;state.snapshotIndex=state.scenarios[state.scenarioIndex].snapshots.length-1}else{return}render()}
function stopPlay(){if(state.timer){clearInterval(state.timer);state.timer=null}$('play').textContent='Play'}
function playNextSnapshot(){const scenario=state.scenarios[state.scenarioIndex];if(state.snapshotIndex>=scenario.snapshots.length-1){stopPlay();return}state.snapshotIndex++;render()}
function togglePlay(){if(state.timer){stopPlay();return}const scenario=state.scenarios[state.scenarioIndex];if(state.snapshotIndex>=scenario.snapshots.length-1){$('play').textContent='Play';return}$('play').textContent='Pause';state.timer=setInterval(playNextSnapshot,4200)}
async function start(){try{const response=await fetch('/api/demo/guard');if(!response.ok)throw new Error('fixture request failed');const payload=await response.json();state.scenarios=payload.scenarios||[];if(!state.scenarios.length)throw new Error('no scenarios');$('intro').hidden=true;$('demo').hidden=false;render()}catch(error){$('load-error').hidden=false;console.error(error)}}
$('start').onclick=start;$('restart').onclick=()=>{stopPlay();state.scenarioIndex=0;state.snapshotIndex=0;render()};$('previous').onclick=previous;$('next').onclick=next;$('play').onclick=togglePlay;
window.addEventListener('keydown',event=>{if($('demo').hidden)return;if(event.key==='ArrowRight'){event.preventDefault();next()}if(event.key==='ArrowLeft'){event.preventDefault();previous()}if(event.key===' '&&event.target===document.body){event.preventDefault();togglePlay()}});
</script>
</body>
</html>'''
